name: goods_traceability_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Injection Dependencies
  injectable:  
  get_it: 

  # UI
  flutter_screenutil: ^5.5.4
  shared_preferences: ^2.0.8
  flutter_svg: 
  google_fonts: ^3.0.1
  file_picker: ^5.0.1
  image_picker: ^0.8.5+3
  font_awesome_flutter: ^10.2.1
  go_router: ^4.5.0
  flutter_animate: ^1.0.0
  freezed_annotation: ^2.1.0
  flutter_native_splash: ^2.2.9
  pinput: ^2.2.12

  # Language
  intl: ^0.17.0
  intl_utils: ^2.7.0
  flutter_localizations:
    sdk: flutter

  # Utils
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  provider: ^6.0.3
  dartz: ^0.10.1
  json_annotation: ^4.6.0

  # Service
  dio: ^4.0.6
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  responsive_framework: ^0.2.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Annotation
  freezed: ^2.1.0+1
  json_serializable:
  # Project
  change_app_package_name:
  # Builder
  injectable_generator:  
 
  go_router_builder:
  flutter_gen_runner:
  build_runner:  

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
    - fonts/
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true
